### PR TITLE
Add secondary index support

### PR DESCRIPTION
**Pull request by k-bx**
This PR adds support for [Secondary Indexes](http://docs.basho.com/riak/latest/dev/using/2i/) support.

### CODE REVIEW

**Comment by markhibberd** [comment]
@k-bx This looks pretty good. Thanks. Give me another day or so to try to do a more detailed review and I will get it merged, and pushed up to hackage (feel free to hassle me if I haven't done so by the weekend).

**Comment by k-bx** [comment]
@markhibberd ok, great!

**Comment by bitemyapp** [comment]
@markhibberd hello hello! Sorry to bother you. What's the status on this?

**Comment by markhibberd** [comment]
Really sorry, slipped off my radar. Will get to it over the weekend.

**Comment by k-bx** [comment]
@markhibberd this is awesome, thanks! Please don't forget to make a hackage release!

**Comment by bitemyapp** [comment]
:heart:

**Comment by markhibberd** [comment]
This is on hackage as `riak-0.8.0.0` and `riak-protobuf-0.19.0.0`. Let me know if you have any issues.

**Comment by k-bx** [comment]
Wonderful, thanks!

**Pull request merged**
