### PR TITLE
Re-run proto.sh with hprotoc 2.4.0

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This is still a WIP

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Okay, got it passing travis. Ready for review.

**Comment by tmcgilchrist** [comment]
Cool, I might hold this one back while I release a bug fix version for cleaning up connection errors.

**Comment by tmcgilchrist** [comment]
Would you mind rebasing and I'll merge this @mitchellwrosen

**Comment by mitchellwrosen** [comment]
Done, thanks @tmcgilchrist

**Pull request merged**
