### PR TITLE
Add simple rollback DSL for testing

### PR DESCRIPTION
**Pull request by mitchellwrosen**
I'd like to improve the test suite in this package a bit, and to that end I've added a (very simplistic) DSL that automatically pairs every `put` with a corresponding `delete`, to keep the state of the database clean between tests. This seems to be the preferred way of cleaning up in between riak tests (another is to rm -rf the data and metedata dirs).

Other rollbacks of global state change (like creating/deleting bucket types) can be added as necessary.

Let me know what you think - I only refactored the two tests in `tests/Properties.hs` so far. I don't want to get too far ahead if it turns out you don't like this idea!

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
That's looks pretty good to me. Feel free to carry on with that if you'd
like to.

I won't be back in front of a computer till at least Tuesday (long weekend
here in Aus). I'll have another look at this then.

**Comment by llelf** [comment]
Be aware that this won't work at all with CRDT ops.

**Comment by mitchellwrosen** [comment]
@llelf Why's that?

**Comment by mitchellwrosen** [comment]
@llelf Ah, I just poked around the CRDT API a bit in hunt for an answer. There doesn't appear to be a way to delete datatypes. Is that what you meant?

In that case, perhaps the simplest way to reset the state of riak between tests is to just `rm -rf <platform_data_dir>/*` and do away with this whole DSL?

**Comment by llelf** [comment]
Yeah, so there’s no way to undo changes.

Between the test suite runs or between individual tests?
I thought about the cleaning, but `rm -rf … && riak restart` is slow, that’s why CRDT test suite just reads the “real state” (as you cannot recreate the state you want) before each test.

**Comment by mitchellwrosen** [comment]
I was thinking between individual tests. Yeah, `riak restart` is slow, but worth it, no? Otherwise, as the test suite grows, you have a greater and greater chance of having some bug due to clobbering the global state that all the tests share.

**Comment by llelf** [comment]
That’s right too.  I just fear that it’ll be *too* slow (I don’t remember if I tried that).

**Comment by llelf** [comment]
`backend = memory` will help I guess

**Comment by mitchellwrosen** [comment]
I did some local testing. On my machine, it takes about 15 seconds to run `riak restart`, then wait for `riak_kv` and `yokozuna` to come back up.

**Comment by mitchellwrosen** [comment]
Closing this as it doesn't address the problem fully

**Pull request closed without merging**
