### PR TITLE
Bump aeson

### PR DESCRIPTION
**Pull request by k-bx**
This will help new stackage

### CODE REVIEW

**Comment by k-bx** [comment]
https://github.com/fpco/stackage/issues/1211

**Comment by tmcgilchrist** [comment]
Cheers.

Was holding off on this to see how aeson 11 would fare in the wild, haven't seen anything reported yet, but still haven't really used it in anger.

**Comment by k-bx** [comment]
@tmcgilchrist could you please make a release so that it's on hackage? This is needed in order to be fixed in nightly stackage

**Comment by k-bx** [comment]
@tmcgilchrist  My company is using aeson 11 for quite some time, but it's somewhat inconvenient having to manually grab it from outside a stackage snapshot, and having to throw another bunch of hacks in order to make dependencies work. I would appreciate if you'd make a hackage release which would bump haskell dependency, it would help leading stackage towards a new nightly, which people would start using "in the wild", report any problems if they're present. After a while, it should go into next major stackage lts release which would bring all the users in. Thanks.

**Comment by tmcgilchrist** [comment]
Uploaded to hackage.
Do let us know if there are any issues.

**Pull request merged**
