### PR TITLE
Use non-forked protocol-buffers

### PR DESCRIPTION
**Pull request by k-bx**
This is my second attempt to use non-forked protocol-buffers libraries.

What I did overall:

- re-checked that current code in riak-haskell-driver/protobuf is the same as generated with latest `hprotoc-fork`
- fixed script to work with gsed if it's present
- regenerated code with new, non-forked `hprotoc`. It turned out mostly the same, except `fno-warn-unused-imports` is added by it (no need for hack in sh-script), and instances of new `TextMsg` and `TextType` were added. I don't really know their purpose to be honest, it seems similar to "show/read" in haskell.
- added stack tool support
- checked that tests work as good as before

### CODE REVIEW

**Comment by k-bx** [comment]
@markhibberd please review. Few possible controversial moments:

1. While adding GHC 7.10 and HEAD support, I dropped support for GHC < 7.8

My motivation:
- I wanted to test with stackage/stack, as many people use it, but they only work with GHC 7.8 and later
- I had some "cabal hell" problems for GHC 7.10 on non-stackage
- GHC 7.6 is already quite old, high chances are people who use it are ok to stick to current riak-haskell-driver
- forked libraries (from which I am migrating) are already stuck with older haskell-src-exts (1.15.*), and probably some other libraries, so sticking to them would lead to more and more frustration from user-side over time, while on the other hand, non-forked are maintained for GHC >= 7.8

2. Usage of stack to test things

I find it very convenient to use stack, especially for Travis, but in case you have anything against it – I can try to use cabal instead. There's a "stackage" package, which provides stackage-related utils to be used with cabal, but in general Haskell infrastructure seems to just move towards stack tool.

Please share your thoughts. Thanks!

**Comment by tmcgilchrist** [comment]
@k-bx I'm ok with dropping support for ghc less than 7.8, in fact I merged something that runs the travis builds against 7.8 and riak 2.0.2 just now. It looks like your travis changes cover more GHC versions which I'm happy to include.

The tests are still an issue in general, in that they don't test much at all. Now that I'm back from ICFP I'm planning on adding more tests for protocol buffers and intergration style running against Riak itself. 
  
As for switching to stack, I don't mind using it.

**Comment by k-bx** [comment]
@tmcgilchrist great to hear you support these changes. I've pushed fixes to merge-conflicts now. Would be happy if you can review & merge.

Regarding testing – also great news. On my side – I rather plan to focus at API simplification, cluster-abstraction and documentation.

**Comment by markhibberd** [comment]
Yep all sounds reasonable to me as well.

**Comment by tmcgilchrist** [comment]
Off topic slightly but I'm interested in looking into the performance
characteristics of the protocol buffer code. I'll open something against
the protocol-buffers project when I've had some time to do some
investigation.

**Comment by k-bx** [comment]
@tmcgilchrist PRs to protocol-buffers are always welcome.

**Comment by k-bx** [comment]
Thanks for merging! Also, please do a hackage release someone.

**Comment by tmcgilchrist** [comment]
Hackage release done 0.9.0.0, please test it out and let us know if there are issues.

**Comment by k-bx** [comment]
Checked by launching our project's tests (which work with riak) – all good :ok_hand:

**Pull request merged**
