### PR TITLE
Release 1.0.2.0.

### PR DESCRIPTION
**Pull request by tmcgilchrist**

### CODE REVIEW

**Comment by qrilka** [comment]
Hi @tmcgilchrist I'm just wondering what is the release process for this library - I think previous releases were pushed to github/hackage without PRs, does this one require some extra review?

**Comment by tmcgilchrist** [comment]
Not really, just trying to follow a less adhoc release process to avoid me messing things up. :-)

**Comment by markhibberd** [comment]
🍧

**Comment by llelf** [comment]
BTW https://github.com/markhibberd/riak-haskell-client/pull/46 potentially (in theory) and definitely (in practice) will change user code behaviour on errors, maybe it's worth a more major version bump.

**Comment by tmcgilchrist** [comment]
Sure, will bump to 1.2.0.0 and release.

**Comment by qrilka** [comment]
@tmcgilchrist but what is the reason to skip 1.1? And commit message says about `1.0.2.0` which is a bit misleading

**Pull request closed without merging**
