### PR TITLE
Use non-forked version of protocol-buffers packages

### PR DESCRIPTION
**Pull request by k-bx**
I took maintainership over protocol-buffers repo, released new package versions and propose to use these packages.

I also add stack tool support. You can now build this package easily by running `stack build`, run all tests by `stack test` and upload package by `stack upload` (this one needs separate run for each package). Very nice tool!

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
I'm not sure about the history of using the forked versions of the various protocol-buffers libraries and tools. I know the code generated differs between the 2 in the various type classes, and won't currently compile without further changes in the calling code in the high level riak client code. I just pushed up a branch with some more details about how the protobuf serialisation code is generated https://github.com/markhibberd/riak-haskell-client/pull/23
Given sufficient time, I'm planning on adding some QuickCheck tests for the serialisation code to give more confidence in them

I'm wary of using stack and would personally prefer to stay with plain cabal. @markhibberd

**Comment by k-bx** [comment]
@tmcgilchrist I didn't try to generate code, thanks for pointing that out, will definitely check.

Regarding stack tool – it doesn't touch usage of cabal-install tool in any way, only adds stack support. So You can use cabal-install (command-line `cabal` tool) just as before.

**Comment by markhibberd** [comment]
@tmcgilchrist @k-bx This history here is that there was a switch to the forked versions because the originals were broken on 7.8 and no-one was able/willing to get a fix pushed in time. I don't have any strong objections to switching back if they are going to be maintained - but will note that a more ideal situation discussed in the past was to move to one of the more performant implementations.

**Comment by k-bx** [comment]
@markhibberd @tmcgilchrist ok, so I finally had some time to check. My results are: there is currently no difference between code generated by hprotoc-fork and hprotoc. @tmcgilchrist you are right indeed, current versions of both add some new code, which we should investigate, but it's not related to this issue and should be handled separately.

I'm doing one additional re-confirmation to re-check myself, but I think we're good.

**Comment by k-bx** [comment]
UPDATE: Ok, my bad, there are some differences (script didn't use executable from variable, so I couldn't notice it). Will investigate.

**Comment by k-bx** [comment]
Closing this PR to open another one.

**Pull request closed without merging**
