### PR TITLE
Make riak host/port configurable in tests

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch adds `tests/test.conf`:

```
# Riak host
host = "localhost"

# Riak protobuf port
port = "8087"

docker {
  # Is Riak running inside a Docker container? If so, execute setup commands
  # (e.g. riak-admin bucket-type create) inside the container.
  enable = false

  # Id or name of the container running Riak
  id = "foo"
}
```

A future patch will make use of the docker variables, but for now, only host/port are read. The end goal is a test suite that can be run locally with `stack test` and not rely on the setup code in `.travis.yml`.

Edit: now, the config looks like this:

-- tests/test.yaml
```
host: localhost
httpPort: 8098
protoPort: 8087
admin: ""
```

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
I'd prefer a solution that can be run either with `cabal` or `stack`, even if that means writing Shell.
Personally I don't use stack and would like to keep this library working with both.

Cheers.

**Comment by mitchellwrosen** [comment]
Sure thing, there are some changes I'd like to make to this patch (after giving it a once-over just now), but I don't see anything stack-specific. `cabal test` should work just as well.

**Comment by mitchellwrosen** [comment]
Hm, tried to fix this up and now I'm getting `Riak network error (Network.Riak.Tag.getTag): invalid riak message code: 47` errors... not too sure what to make of it at the moment. Message code 47 doesn't exist.

**Comment by mitchellwrosen** [comment]
Oh, I was hitting the protobuf API over the HTTP endpoint =)

**Comment by mitchellwrosen** [comment]
Ok, once I get this passing travis, it's ready for review.

**Comment by mitchellwrosen** [comment]
Ok, passing :+1:

**Comment by mitchellwrosen** [comment]
I think this is obsolete now that #73 was merged, which built on this.

**Pull request closed without merging**
